name: Portfolio CI

on:
  push:
    branches:
      - react

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    environment:
      name: ghp-react-deploy
      url: https://louis-manabat.github.io
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install npm packages
        run: npm ci